<?php

return [
    [
        "title" => "Spotify Web",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "No",
        "image" => "uploads/spotifyweb.png",
        "description" => "A clone of the spotify web interface",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-spotifyweb.git",
    ],

    [
        "title" => "Campo Minato",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-27",
        "collaborators" => "No",
        "image" => "uploads/campominato.png",
        "description" => "A minefield clone",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-campominato-dom.git",
    ],

    [
        "title" => "Social Post",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-04",
        "collaborators" => "No",
        "image" => "uploads/socialpost.png",
        "description" => "A Facebook clone",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-social-posts.git",
    ],

    [
        "title" => "Boolzapp",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-15",
        "collaborators" => "No",
        "image" => "uploads/boolzapp.png",
        "description" => "A Whatsapp clone",
        "technologies" => [4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vite-boolflix.git",
    ],

    [
        "title" => "School Chess",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-05-31",
        "collaborators" => "No",
        "image" => "uploads/schoolchess.png",
        "description" => "Avada Driving clone",
        "technologies" => [4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/proj-html-vuejs.git",
    ],

    [
        "title" => "DC Comics",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-29",
        "last_update" => "2023-07-03",
        "collaborators" => "No",
        "image" => "uploads/dccomics.png",
        "description" => "A Dc Comics site homepage clone",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-dc-comics.git",
    ],

    [
        "title" => "Laravel Boolean",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Paolo Falco, Antonio Nicolaci, Alessandra Casu, Gary Smith Alvarez Venturo, Renato Taccogna, Pierluca Strianese",
        "image" => "uploads/laravelboolean.png",
        "description" => "A invoices organizer",
        "technologies" => [6, 7],
        "type_id" => 3,
        "link_github" => "https://github.com/Paolo96700/laravel-boolean.git",
    ],
];
